version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
